spring:
  application:
    name: product-service-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lovesale_product
    username: root
    password: root
server:
  port: 8002

mybatis-plus:
  mapper-locations: classpath:uu/qrsource/lovesale/mapper/*Mapper.xml
  type-aliases-package: uu.qrsource.lovesale.entity,uu.qrsource.lovesale.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true  
